spi:
  # extension spring 两种加载模式
  tool: spring


spring:
  redis:
    host: 112.74.163.239
    port: 6379
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0